services:
  couchdb:
    container_name: next-couchdb
    image: couchdb:3.4.2
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: always

volumes:
  couchdb_data: